// <auto-generated />
using ExamNet6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamNet6.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221209080511_AddTimeToTasksAndSeedData")]
    partial class AddTimeToTasksAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamNet6.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Time")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = 0,
                            Status = 1,
                            Text = "Do web api with React front",
                            Time = 1.1f,
                            Title = "Exam"
                        },
                        new
                        {
                            Id = 2,
                            Priority = 1,
                            Status = 1,
                            Text = "Seed db",
                            Time = 0.2f,
                            Title = "Exam"
                        },
                        new
                        {
                            Id = 3,
                            Priority = 0,
                            Status = 0,
                            Text = "Go to work",
                            Time = 4f,
                            Title = "Post exam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
